!if "$(PLAT)" == "Win32"
EXTRA_LIBTEXTSTYLE_SRCS =	\
	..\libtextstyle\lib\calloc.c	\
	..\libtextstyle\lib\malloc.c
!endif

LIBTEXTSTYLE_BASE_SRCS =	\
	..\libtextstyle\lib\asnprintf.c	\
	..\libtextstyle\lib\asprintf.c	\
	..\libtextstyle\lib\aszprintf.c	\
	..\libtextstyle\lib\basename-lgpl.c	\
	..\libtextstyle\lib\binary-io.c	\
	..\libtextstyle\lib\c-ctype.c	\
	..\libtextstyle\lib\c-strcasecmp.c	\
	..\libtextstyle\lib\c-strncasecmp.c	\
	..\libtextstyle\lib\c32isalnum.c	\
	..\libtextstyle\lib\c32isalpha.c	\
	..\libtextstyle\lib\c32isblank.c	\
	..\libtextstyle\lib\c32iscntrl.c	\
	..\libtextstyle\lib\c32isdigit.c	\
	..\libtextstyle\lib\c32isgraph.c	\
	..\libtextstyle\lib\c32islower.c	\
	..\libtextstyle\lib\c32isprint.c	\
	..\libtextstyle\lib\c32ispunct.c	\
	..\libtextstyle\lib\c32isspace.c	\
	..\libtextstyle\lib\c32isupper.c	\
	..\libtextstyle\lib\c32isxdigit.c	\
	..\libtextstyle\lib\c32tolower.c	\
	..\libtextstyle\lib\c32width.c	\
	..\libtextstyle\lib\cloexec.c	\
	..\libtextstyle\lib\close.c	\
	..\libtextstyle\lib\color.c	\
	..\libtextstyle\lib\concat-filename.c	\
	..\libtextstyle\lib\dup2.c	\
	..\libtextstyle\lib\error.c	\
	..\libtextstyle\lib\exitfail.c	\
	..\libtextstyle\lib\fatal-signal.c	\
	..\libtextstyle\lib\fcntl.c	\
	..\libtextstyle\lib\fd-hook.c	\
	..\libtextstyle\lib\fd-ostream.c	\
	..\libtextstyle\lib\file-ostream.c	\
	..\libtextstyle\lib\float.c	\
	..\libtextstyle\lib\free.c	\
	..\libtextstyle\lib\fstat.c	\
	..\libtextstyle\lib\fsync.c	\
	..\libtextstyle\lib\full-write.c	\
	..\libtextstyle\lib\getdtablesize.c	\
	..\libtextstyle\lib\gethostname.c	\
	..\libtextstyle\lib\getprogname.c	\
	..\libtextstyle\lib\gettimeofday.c	\
	..\libtextstyle\lib\get_ppid_of.c	\
	..\libtextstyle\lib\get_progname_of.c	\
	..\libtextstyle\lib\gl_array_list.c	\
	..\libtextstyle\lib\gl_list.c	\
	..\libtextstyle\lib\gl_xlist.c	\
	..\libtextstyle\lib\hard-locale.c	\
	..\libtextstyle\lib\html-ostream.c	\
	..\libtextstyle\lib\html-styled-ostream.c	\
	..\libtextstyle\lib\ialloc.c	\
	..\libtextstyle\lib\iconv-ostream.c	\
	..\libtextstyle\lib\isatty.c	\
	..\libtextstyle\lib\isinf.c	\
	..\libtextstyle\lib\isnand.c	\
	..\libtextstyle\lib\isnanf.c	\
	..\libtextstyle\lib\isnanl.c	\
	..\libtextstyle\lib\localcharset.c	\
	..\libtextstyle\lib\malloca.c	\
	..\libtextstyle\lib\math.c	\
	..\libtextstyle\lib\mbchar.c	\
	..\libtextstyle\lib\mbiterf.c	\
	..\libtextstyle\lib\mbrtoc32.c	\
	..\libtextstyle\lib\mbrtowc.c	\
	..\libtextstyle\lib\mbsinit.c	\
	..\libtextstyle\lib\mbsnlen.c	\
	..\libtextstyle\lib\mbszero.c	\
	..\libtextstyle\lib\mem-hash-map.c	\
	..\libtextstyle\lib\memory-ostream.c	\
	..\libtextstyle\lib\misc.c	\
	..\libtextstyle\lib\msvc-inval.c	\
	..\libtextstyle\lib\msvc-nothrow.c	\
	..\libtextstyle\lib\next-prime.c	\
	..\libtextstyle\lib\noop-styled-ostream.c	\
	..\libtextstyle\lib\obstack.c	\
	..\libtextstyle\lib\open.c	\
	..\libtextstyle\lib\ostream.c	\
	..\libtextstyle\lib\printf-args.c	\
	..\libtextstyle\lib\printf-frexp.c	\
	..\libtextstyle\lib\printf-frexpl.c	\
	..\libtextstyle\lib\printf-parse.c	\
	..\libtextstyle\lib\pthread-once.c	\
	..\libtextstyle\lib\raise.c	\
	..\libtextstyle\lib\read.c	\
	..\libtextstyle\lib\realloc.c	\
	..\libtextstyle\lib\reallocarray.c	\
	..\libtextstyle\lib\safe-read.c	\
	..\libtextstyle\lib\safe-write.c	\
	..\libtextstyle\lib\same-inode.c	\
	..\libtextstyle\lib\setlocale_null-unlocked.c	\
	..\libtextstyle\lib\setlocale_null.c	\
	..\libtextstyle\lib\sig-handler.c	\
	..\libtextstyle\lib\sigaction.c	\
	..\libtextstyle\lib\sigprocmask.c	\
	..\libtextstyle\lib\snprintf.c	\
	..\libtextstyle\lib\sockets.c	\
	..\libtextstyle\lib\stat-time.c	\
	..\libtextstyle\lib\stat-w32.c	\
	..\libtextstyle\lib\stat.c	\
	..\libtextstyle\lib\stdlib.c	\
	..\libtextstyle\lib\stpcpy.c	\
	..\libtextstyle\lib\strerror-override.c	\
	..\libtextstyle\lib\strerror.c	\
	..\libtextstyle\lib\str_endswith.c	\
	..\libtextstyle\lib\str_startswith.c	\
	..\libtextstyle\lib\styled-ostream.c	\
	..\libtextstyle\lib\sys_socket.c	\
	..\libtextstyle\lib\term-ostream.c	\
	..\libtextstyle\lib\term-style-control.c	\
	..\libtextstyle\lib\term-styled-ostream.c	\
	..\libtextstyle\lib\tparm.c	\
	..\libtextstyle\lib\tputs.c	\
	..\libtextstyle\lib\unistd.c	\
	..\libtextstyle\lib\vasnprintf.c	\
	..\libtextstyle\lib\vasprintf.c	\
	..\libtextstyle\lib\vaszprintf.c	\
	..\libtextstyle\lib\version.c	\
	..\libtextstyle\lib\vsnprintf.c	\
	..\libtextstyle\lib\vsnzprintf.c	\
	..\libtextstyle\lib\wctype-h.c	\
	..\libtextstyle\lib\wcwidth.c	\
	..\libtextstyle\lib\windows-mutex.c	\
	..\libtextstyle\lib\windows-once.c	\
	..\libtextstyle\lib\windows-recmutex.c	\
	..\libtextstyle\lib\windows-rwlock.c	\
	..\libtextstyle\lib\write.c	\
	..\libtextstyle\lib\xalloc-die.c	\
	..\libtextstyle\lib\xasprintf.c	\
	..\libtextstyle\lib\xconcat-filename.c	\
	..\libtextstyle\lib\xgethostname.c	\
	..\libtextstyle\lib\xmalloc.c	\
	..\libtextstyle\lib\xsize.c	\
	..\libtextstyle\lib\xvasprintf.c	\
	$(EXTRA_LIBTEXTSTYLE_SRCS)
